export const FEATURE_CATALOG = [
  // Navigation / shell
  { group: 'main', key: 'dashboard', label: 'Dashboard', defaultEnabled: true },
  { group: 'main', key: 'dashboard_2', label: 'Dashboard 2', defaultEnabled: true },
  { group: 'main', key: 'sales_dashboard', label: 'Sales Dashboard', defaultEnabled: true },
  { group: 'main', key: 'messages', label: 'Messages', defaultEnabled: true },
  { group: 'main', key: 'layout_settings', label: 'Layout Settings', defaultEnabled: true },
  { group: 'navigation', key: 'main_menu', label: 'Main Menu', defaultEnabled: true },
  { group: 'navigation', key: 'application', label: 'Application Section', defaultEnabled: true },
  { group: 'navigation', key: 'layouts', label: 'Layouts Section', defaultEnabled: true },
  { group: 'navigation', key: 'products_section', label: 'Products Section', defaultEnabled: true },
  { group: 'navigation', key: 'stock_section', label: 'Stock Section', defaultEnabled: true },
  { group: 'navigation', key: 'sales_section', label: 'Sales Section', defaultEnabled: true },
  { group: 'navigation', key: 'promo_section', label: 'Promo Section', defaultEnabled: true },
  { group: 'navigation', key: 'purchases_section', label: 'Purchases Section', defaultEnabled: true },
  { group: 'navigation', key: 'finance_section', label: 'Finance & Accounts Section', defaultEnabled: true },
  { group: 'navigation', key: 'people_section', label: 'Peoples Section', defaultEnabled: true },
  { group: 'navigation', key: 'hrm_section', label: 'HRM Section', defaultEnabled: true },
  { group: 'navigation', key: 'reports_section', label: 'Reports Section', defaultEnabled: true },
  { group: 'navigation', key: 'cms_section', label: 'Content (CMS) Section', defaultEnabled: true },
  { group: 'navigation', key: 'user_management_section', label: 'User Management Section', defaultEnabled: true },
  { group: 'navigation', key: 'settings_section', label: 'Settings Section', defaultEnabled: true },
  { group: 'navigation', key: 'super_admin_section', label: 'Super Admin Section', defaultEnabled: true },
  // Header / shell
  { group: 'header', key: 'search', label: 'Header Search', defaultEnabled: true },
  { group: 'header', key: 'store_switcher', label: 'Store Switcher', defaultEnabled: true },
  { group: 'header', key: 'quick_actions', label: 'Quick Actions Menu', defaultEnabled: true },
  { group: 'header', key: 'pos_shortcut', label: 'POS Shortcut', defaultEnabled: true },
  { group: 'header', key: 'language_switcher', label: 'Language Switcher', defaultEnabled: true },
  { group: 'header', key: 'fullscreen', label: 'Fullscreen Toggle', defaultEnabled: true },
  { group: 'header', key: 'notifications', label: 'Notifications', defaultEnabled: true },
  { group: 'header', key: 'messages_shortcut', label: 'Messages Shortcut', defaultEnabled: true },
  { group: 'header', key: 'settings_shortcut', label: 'Settings Shortcut', defaultEnabled: true },
  { group: 'header', key: 'profile_link', label: 'Profile Link', defaultEnabled: true },
  { group: 'header', key: 'reports_link', label: 'Reports Link', defaultEnabled: true },
  // POS — Core
  { group: 'pos', key: 'pos_terminal', label: 'POS Terminal', defaultEnabled: true },
  { group: 'pos', key: 'barcode_scanner', label: 'Barcode Scanner', defaultEnabled: true },
  { group: 'pos', key: 'receipt_printing', label: 'Receipt Printing', defaultEnabled: true },
  { group: 'pos', key: 'ticket_printing', label: 'Ticket Printing (kuzhinë/barista)', defaultEnabled: false },
  { group: 'pos', key: 'fiscalization', label: 'Fiskalizim (tatimor)', defaultEnabled: false },
  { group: 'pos', key: 'offline_mode', label: 'Offline Mode', defaultEnabled: false },
  // POS — Payment Summary rows
  { group: 'pos', key: 'shipping', label: 'Shipping Fee', defaultEnabled: true },
  { group: 'pos', key: 'tax', label: 'Tax Calculation', defaultEnabled: true },
  { group: 'pos', key: 'coupon', label: 'Coupon Codes', defaultEnabled: true },
  { group: 'pos', key: 'order_discount', label: 'Order Discount', defaultEnabled: true },
  { group: 'pos', key: 'roundoff', label: 'Round Off', defaultEnabled: true },
  // POS — Action buttons
  { group: 'pos', key: 'hold_orders', label: 'Hold Orders', defaultEnabled: true },
  { group: 'pos', key: 'void_orders', label: 'Void / Cancel Orders', defaultEnabled: true },
  // POS — Payment methods
  { group: 'pos', key: 'pay_cash', label: 'Payment: Cash', defaultEnabled: true },
  { group: 'pos', key: 'pay_card', label: 'Payment: Card', defaultEnabled: true },
  { group: 'pos', key: 'pay_points', label: 'Payment: Points', defaultEnabled: true },
  { group: 'pos', key: 'pay_deposit', label: 'Payment: Deposit', defaultEnabled: true },
  { group: 'pos', key: 'pay_cheque', label: 'Payment: Cheque', defaultEnabled: true },
  { group: 'pos', key: 'pay_gift_card', label: 'Payment: Gift Card', defaultEnabled: false },
  { group: 'pos', key: 'pay_scan', label: 'Payment: QR/Scan', defaultEnabled: false },
  { group: 'pos', key: 'pay_later', label: 'Payment: Pay Later', defaultEnabled: false },
  { group: 'pos', key: 'pay_external', label: 'Payment: External', defaultEnabled: false },
  { group: 'pos', key: 'pay_split', label: 'Payment: Split Bill', defaultEnabled: false },
  // Sales
  { group: 'sales', key: 'sales_orders', label: 'Sales Orders', defaultEnabled: true },
  { group: 'sales', key: 'all_sales', label: 'All Sales', defaultEnabled: true },
  { group: 'sales', key: 'online_sales', label: 'Online Sales', defaultEnabled: true },
  { group: 'sales', key: 'pos_sales', label: 'POS Sales', defaultEnabled: true },
  { group: 'sales', key: 'sales_invoices', label: 'Invoices', defaultEnabled: true },
  { group: 'sales', key: 'returns_refunds', label: 'Returns & Refunds', defaultEnabled: true },
  { group: 'sales', key: 'layaway', label: 'Layaway / Holds', defaultEnabled: false },
  { group: 'sales', key: 'quotations', label: 'Quotations', defaultEnabled: false },
  // Inventory
  { group: 'inventory', key: 'product_variants', label: 'Product Variants', defaultEnabled: true },
  { group: 'inventory', key: 'stock_alerts', label: 'Low Stock Alerts', defaultEnabled: true },
  { group: 'inventory', key: 'multi_warehouse', label: 'Multi-Warehouse', defaultEnabled: true },
  { group: 'inventory', key: 'expiry_tracking', label: 'Expiry Date Tracking', defaultEnabled: false },
  { group: 'inventory', key: 'serial_numbers', label: 'Serial Number Tracking', defaultEnabled: false },
  { group: 'inventory', key: 'products_list', label: 'Products List', defaultEnabled: true },
  { group: 'inventory', key: 'categories', label: 'Categories', defaultEnabled: true },
  { group: 'inventory', key: 'sub_categories', label: 'Sub Categories', defaultEnabled: true },
  { group: 'inventory', key: 'brands', label: 'Brands', defaultEnabled: true },
  { group: 'inventory', key: 'units', label: 'Units', defaultEnabled: true },
  { group: 'inventory', key: 'variant_attributes', label: 'Variant Attributes', defaultEnabled: true },
  { group: 'inventory', key: 'warranties', label: 'Warranties', defaultEnabled: true },
  { group: 'inventory', key: 'barcode_printing', label: 'Print Barcode', defaultEnabled: true },
  { group: 'inventory', key: 'qr_printing', label: 'Print QR Code', defaultEnabled: true },
  { group: 'inventory', key: 'stock_management', label: 'Manage Stock', defaultEnabled: true },
  { group: 'inventory', key: 'stock_adjustment', label: 'Stock Adjustment', defaultEnabled: true },
  { group: 'inventory', key: 'stock_transfer', label: 'Stock Transfer', defaultEnabled: true },
  // Purchasing
  { group: 'purchasing', key: 'purchase_orders', label: 'Purchase Orders', defaultEnabled: true },
  { group: 'purchasing', key: 'supplier_management', label: 'Supplier Management', defaultEnabled: true },
  { group: 'purchasing', key: 'purchases_list', label: 'Purchases', defaultEnabled: true },
  { group: 'purchasing', key: 'purchase_returns', label: 'Purchase Return', defaultEnabled: true },
  // HR
  { group: 'hr', key: 'employee_management', label: 'Employee Management', defaultEnabled: true },
  { group: 'hr', key: 'attendance', label: 'Attendance Tracking', defaultEnabled: true },
  { group: 'hr', key: 'payroll', label: 'Payroll', defaultEnabled: false },
  { group: 'hr', key: 'leave_management', label: 'Leave Management', defaultEnabled: false },
  { group: 'hr', key: 'employees', label: 'Employees', defaultEnabled: true },
  { group: 'hr', key: 'departments', label: 'Departments', defaultEnabled: true },
  { group: 'hr', key: 'designation', label: 'Designation', defaultEnabled: true },
  { group: 'hr', key: 'shifts', label: 'Shifts', defaultEnabled: true },
  { group: 'hr', key: 'attendance_employee', label: 'Attendance: Employee', defaultEnabled: true },
  { group: 'hr', key: 'attendance_admin', label: 'Attendance: Admin', defaultEnabled: true },
  { group: 'hr', key: 'leave_admin', label: 'Leaves: Admin', defaultEnabled: false },
  { group: 'hr', key: 'leave_employee', label: 'Leaves: Employee', defaultEnabled: false },
  { group: 'hr', key: 'leave_types', label: 'Leave Types', defaultEnabled: false },
  { group: 'hr', key: 'holidays', label: 'Holidays', defaultEnabled: false },
  { group: 'hr', key: 'payroll_employee_salary', label: 'Employee Salary', defaultEnabled: false },
  { group: 'hr', key: 'payroll_payslip', label: 'Payslip', defaultEnabled: false },
  // Finance
  { group: 'finance', key: 'bank_accounts', label: 'Bank Accounts', defaultEnabled: true },
  { group: 'finance', key: 'expense_tracking', label: 'Expense Tracking', defaultEnabled: true },
  { group: 'finance', key: 'financial_reports', label: 'Financial Reports', defaultEnabled: true },
  { group: 'finance', key: 'expenses', label: 'Expenses', defaultEnabled: true },
  { group: 'finance', key: 'expense_categories', label: 'Expense Category', defaultEnabled: true },
  { group: 'finance', key: 'income', label: 'Income', defaultEnabled: true },
  { group: 'finance', key: 'income_categories', label: 'Income Category', defaultEnabled: true },
  { group: 'finance', key: 'money_transfer', label: 'Money Transfer', defaultEnabled: true },
  { group: 'finance', key: 'balance_sheet', label: 'Balance Sheet', defaultEnabled: true },
  { group: 'finance', key: 'trial_balance', label: 'Trial Balance', defaultEnabled: true },
  { group: 'finance', key: 'cash_flow', label: 'Cash Flow', defaultEnabled: true },
  { group: 'finance', key: 'account_statement', label: 'Account Statement', defaultEnabled: true },
  // Marketing
  { group: 'marketing', key: 'coupons', label: 'Coupons & Discounts', defaultEnabled: true },
  { group: 'marketing', key: 'gift_cards', label: 'Gift Cards', defaultEnabled: true },
  { group: 'marketing', key: 'product_discounts', label: 'Product Discount', defaultEnabled: true },
  { group: 'marketing', key: 'category_discounts', label: 'Category Discount', defaultEnabled: true },
  { group: 'marketing', key: 'loyalty_program', label: 'Loyalty Program', defaultEnabled: false },
  // CMS
  { group: 'cms', key: 'blog', label: 'Blog', defaultEnabled: false },
  { group: 'cms', key: 'pages', label: 'CMS Pages', defaultEnabled: false },
  { group: 'cms', key: 'testimonials', label: 'Testimonials', defaultEnabled: false },
  { group: 'cms', key: 'blog_tags', label: 'Blog Tags', defaultEnabled: false },
  { group: 'cms', key: 'blog_categories', label: 'Blog Categories', defaultEnabled: false },
  { group: 'cms', key: 'blog_comments', label: 'Blog Comments', defaultEnabled: false },
  { group: 'cms', key: 'countries', label: 'Countries', defaultEnabled: false },
  { group: 'cms', key: 'states', label: 'States', defaultEnabled: false },
  { group: 'cms', key: 'cities', label: 'Cities', defaultEnabled: false },
  { group: 'cms', key: 'faq', label: 'FAQ', defaultEnabled: false },
  // Reports
  { group: 'reports', key: 'sales_reports', label: 'Sales Reports', defaultEnabled: true },
  { group: 'reports', key: 'inventory_reports', label: 'Inventory Reports', defaultEnabled: true },
  { group: 'reports', key: 'hr_reports', label: 'HR Reports', defaultEnabled: false },
  { group: 'reports', key: 'best_seller', label: 'Best Seller', defaultEnabled: true },
  { group: 'reports', key: 'purchase_report', label: 'Purchase Report', defaultEnabled: true },
  { group: 'reports', key: 'stock_history', label: 'Stock History', defaultEnabled: true },
  { group: 'reports', key: 'sold_stock', label: 'Sold Stock', defaultEnabled: true },
  { group: 'reports', key: 'invoice_report', label: 'Invoice Report', defaultEnabled: true },
  { group: 'reports', key: 'supplier_report', label: 'Supplier Report', defaultEnabled: true },
  { group: 'reports', key: 'supplier_due', label: 'Supplier Due', defaultEnabled: true },
  { group: 'reports', key: 'customer_report', label: 'Customer Report', defaultEnabled: true },
  { group: 'reports', key: 'customer_due', label: 'Customer Due', defaultEnabled: true },
  { group: 'reports', key: 'product_report', label: 'Product Report', defaultEnabled: true },
  { group: 'reports', key: 'product_expiry_report', label: 'Product Expiry Report', defaultEnabled: true },
  { group: 'reports', key: 'product_quantity_alert', label: 'Product Quantity Alert', defaultEnabled: true },
  { group: 'reports', key: 'expense_report', label: 'Expense Report', defaultEnabled: true },
  { group: 'reports', key: 'income_report', label: 'Income Report', defaultEnabled: true },
  { group: 'reports', key: 'tax_report', label: 'Tax Report', defaultEnabled: true },
  { group: 'reports', key: 'sales_tax_report', label: 'Sales Tax', defaultEnabled: true },
  { group: 'reports', key: 'profit_loss', label: 'Profit & Loss', defaultEnabled: true },
  { group: 'reports', key: 'annual_report', label: 'Annual Report', defaultEnabled: true },
  // People / Users / Settings / Super Admin navigation
  { group: 'people', key: 'customers', label: 'Customers', defaultEnabled: true },
  { group: 'people', key: 'billers', label: 'Billers', defaultEnabled: true },
  { group: 'people', key: 'suppliers', label: 'Suppliers', defaultEnabled: true },
  { group: 'people', key: 'stores', label: 'Stores', defaultEnabled: true },
  { group: 'people', key: 'warehouses', label: 'Warehouses', defaultEnabled: true },
  { group: 'people', key: 'users', label: 'Users', defaultEnabled: true },
  { group: 'users', key: 'roles_permissions', label: 'Roles & Permissions', defaultEnabled: true },
  { group: 'users', key: 'delete_account_requests', label: 'Delete Account Request', defaultEnabled: true },
  { group: 'settings', key: 'security', label: 'Security', defaultEnabled: true },
  { group: 'settings', key: 'notifications', label: 'Notifications', defaultEnabled: true },
  { group: 'settings', key: 'connected_apps', label: 'Connected Apps', defaultEnabled: true },
  { group: 'settings', key: 'website_settings', label: 'Website Settings', defaultEnabled: true },
  { group: 'settings', key: 'app_settings', label: 'App Settings', defaultEnabled: true },
  { group: 'settings', key: 'system_settings', label: 'System Settings', defaultEnabled: true },
  { group: 'settings', key: 'financial_settings', label: 'Financial Settings', defaultEnabled: true },
  { group: 'settings', key: 'other_settings', label: 'Other Settings', defaultEnabled: true },
  { group: 'super_admin', key: 'super_admin_dashboard', label: 'Dashboard', defaultEnabled: true },
  { group: 'super_admin', key: 'companies', label: 'Companies', defaultEnabled: true },
  { group: 'super_admin', key: 'feature_management', label: 'Feature Management', defaultEnabled: true },
  { group: 'super_admin', key: 'subscriptions', label: 'Subscriptions', defaultEnabled: true },
  { group: 'super_admin', key: 'packages', label: 'Packages', defaultEnabled: true },
  { group: 'super_admin', key: 'domain', label: 'Domain', defaultEnabled: true },
  { group: 'super_admin', key: 'purchase_transactions', label: 'Purchase Transaction', defaultEnabled: true },
  { group: 'super_admin', key: 'super_admin_settings', label: 'Settings', defaultEnabled: true },
] as const;

export type FeatureCatalogItem = (typeof FEATURE_CATALOG)[number];